---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml
      tags: ['always']

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']
    - role: startup
      when: configure_startup
      tags: ['startup']
    - role: danbohea.macos-spelling
      tags: ["spelling"]
    - role: danbohea.google-chrome
      tags: ['chrome']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']

  tasks:
    - include: tasks/ansible-setup.yml

    - include: tasks/firefox.yml
      tags: ['firefox']

    - include: tasks/ssh.yml
      tags: ['ssh']

    - include: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - include: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - include: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - include: tasks/sourcetree.yml
      tags: ['sourcetree']

    - include: tasks/iterm2.yml
      tags: ['iterm2']

    - include: tasks/extra-packages.yml
      tags: ['extra-packages']

    - name: Run configured post-provision ansible task files.
      include: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
